config/routes.rb
Rails.application.routes.draw do
  resources :replies

  resources :posts

  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resource :user
  devise_for :users, controllers: { registrations: "users/registrations" }

  root 'posts#index'

  get '/:id' => 'contents#show'
  get '/replies/new/:post_id' => 'replies#new'
  get 'contents/downloadpdf/download'=> 'contents#downloadpdf'

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  acts_as_paranoid

  validates :text, presence: true
end

app/controllers/replies_controller.rb
# -*- coding: utf-8 -*-
class RepliesController < ApplicationController
  before_action :set_reply, only: [:show, :edit, :update, :destroy]
  before_action :set_post, only: [:new, :create]

  respond_to :html

  # # GET /replies
  # # GET /replies.json
  # def index
  #   @replies = Reply.all
  # end

  # # GET /replies/1
  # # GET /replies/1.json
  # def show
  # end

  # GET /replies/new
  def new
    @reply = Reply.new
    session[:post_id] = @post.id
  end

  # # GET /replies/1/edit
  # def edit
  # end

  # POST /replies
  # POST /replies.json
  def create
    @reply = Reply.new(reply_params)
    @reply.user = current_user if current_user
    @post = Post.find(session[:post_id])
    @reply.post = @post

    body = @reply.text
    jp_length = body.gsub(/[a-zA-Z0-9,.;:'"_\[\]<>\/= ]/, "").to_s.split(//).size
    body_length = body.split(//).size

    if jp_length < body_length * 0.2
      flash[:alert] = "スパム投稿防止の為、受け付けできません。"
      redirect_to root_path
    elsif @reply.save
      ReplyMailer.new_reply_email(@reply).deliver_now

      session[:post_id] = nil
      flash[:notice] = "情報提供ありがとうございました！"
      respond_with(@post, location: post_path(@post))
    else
      respond_with(@reply)
    end
  end

  # # PATCH/PUT /replies/1
  # # PATCH/PUT /replies/1.json
  # def update
  #   respond_to do |format|
  #     if @reply.update(reply_params)
  #       format.html { redirect_to @reply, notice: 'Reply was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @reply }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @reply.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /replies/1
  # # DELETE /replies/1.json
  # def destroy
  #   @reply.destroy
  #   respond_to do |format|
  #     format.html { redirect_to replies_url, notice: 'Reply was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_reply
    @reply = Reply.find(params[:id])
  end

  def set_post
    if !params[:post_id].nil?
      @post = Post.find(params[:post_id])
    elsif !session[:post_id].nil?
      @post = Post.find(session[:post_id])
    else
      flash[:alert] = "Invalid Params"
      redirect_to posts_path
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def reply_params
    params.require(:reply).permit(:user_id, :post_id, :text)
  end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_form.html.haml
= form_for(@reply) do |f|
  - if @reply.errors.any?
    #error_explanation
      %h2
        = pluralize(@reply.errors.count, "error")
        prohibited this reply from being saved:
      %ul
        - @reply.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :text
    = f.text_area :text, rows: 5, class: "form-control"

  %table.table.table-striped.table-bordered
    %tr
      %td= @post.title
    %tr
      %td
        %ul
          %li
            - if @post.images
              - @post.images.each do |image|
                = link_to image_tag(image.url(:thumb)), image.url(:medium), "data-lightbox" => image.url(:medium)
          %li= "#{t('activerecord.attributes.post.location')}: #{@post.location}"
          %li= "#{t('activerecord.attributes.post.date')}: #{@post.date.strftime('%Y/%m/%d')}"
          %li= "#{t('activerecord.attributes.post.chassis_number')}: #{@post.chassis_number}"
          %li= "#{t('activerecord.attributes.post.registration_number')}: #{@post.registration_number}"
          %li= "#{t('activerecord.attributes.post.features')}: #{@post.features}"
          %li= "#{t('activerecord.attributes.post.situation')}: #{@post.situation}"
        .right
          .user-info
            - if @post.user && @post.user.image
              = link_to image_tag(@post.user.image.url(:thumb), height:60), @post.user.image.url(:medium), "data-lightbox" => @post.user.image.url(:medium)
            = @post.user.name
            %span.small= @post.created_at.strftime("%Y/%m/%d %H:%M")

  .actions
    = f.submit t("links.reply.submit"), class: "btn btn-success"
    = link_to t("links.back"), :back, class: "btn btn-default", data: {no_turbolink: true}

app/views/replies/edit.html.haml
%h1 Editing Reply
= render 'form'
= link_to 'Show', @reply
|
= link_to 'Back', replies_path

app/views/replies/index.html.haml
%p#notice= notice
%h1 Listing Replies
%table
  %thead
    %tr
      %th User
      %th Post
      %th Text
      %th{:colspan => "3"}
  %tbody
    - @replies.each do |reply|
      %tr
        %td= reply.user
        %td= reply.post
        %td= reply.text
        %td= link_to 'Show', reply
        %td= link_to 'Edit', edit_reply_path(reply)
        %td= link_to 'Destroy', reply, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Reply', new_reply_path

app/views/replies/new.html.haml
.center
  %h2
    = t("links.new") + t("activerecord.models.reply")
.narrow
  = render 'form'

app/views/replies/show.html.haml
%p#notice= notice
%p
  %strong User:
  = @reply.user
%p
  %strong Post:
  = @reply.post
%p
  %strong Text:
  = @reply.text
= link_to 'Edit', edit_reply_path(@reply)
|
= link_to 'Back', replies_path