config/routes.rb
Rails.application.routes.draw do
  resources :replies

  resources :posts

  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resource :user
  devise_for :users, controllers: { registrations: "users/registrations" }

  root 'posts#index'

  get '/:id' => 'contents#show'
  get '/replies/new/:post_id' => 'replies#new'
  get 'contents/downloadpdf/download'=> 'contents#downloadpdf'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :images, as: :imageable
  accepts_nested_attributes_for :images

  acts_as_paranoid

  validates :title, :location, presence: true
end

app/controllers/posts_controller.rb
# -*- coding: utf-8 -*-
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  respond_to :html

  # GET /posts
  # GET /posts.json
  def index
    if params[:keyword]
      @posts = Post.includes(:images, :user).where("title LIKE ? OR location LIKE ? OR model LIKE ? OR chassis_number LIKE ? OR registration_number LIKE ?", "%#{params[:keyword]}%", "%#{params[:keyword]}%", "%#{params[:keyword]}%", "%#{params[:keyword]}%", "%#{params[:keyword]}%").order("created_at DESC").page(params[:page]).per(10)
       # Post.arel_table[:title].matches("%#{params[:keyword]}%") OR Post.arel_table[:location].matches("%#{params[:keyword]}%") OR Post.arel_table[:model].matches("%#{params[:keyword]}%") OR Post.arel_table[:chassis_number].matches("%#{params[:keyword]}%") OR Post.arel_table[:registration_number].matches("%#{params[:keyword]}%") OR Post.arel_table[:features].matches("%#{params[:keyword]}%") OR Post.arel_table[:situation].matches("%#{params[:keyword]}%")
    else
      @posts = Post.includes(:images, :user).order("created_at DESC").page(params[:page]).per(10)
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @description = @post.title
    @keywords = @post.model
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.images.build
  end

  # GET /posts/1/edit
  def edit
    @post.images.build
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    body = @post.situation
    jp_length = body.gsub(/[a-zA-Z0-9,.;:'"_\[\]<>\/= ]/, "").to_s.split(//).size
    body_length = body.split(//).size

    if jp_length < body_length * 0.5
      flash[:alert] = "スパム投稿防止の為、受け付けできません。"
      redirect_to root_path
    elsif @post.save
      if params[:post][:images]
        params[:post][:images].each_with_index { |image, i|
          return if i > 2
          @post.images.create(user: current_user, image: image)
        }
      end
      flash[:notice] = "投稿しました。"
      respond_with(@post, location: post_path(@post))
    else
      respond_with(@post)
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: t("activerecord.models.post") + t("messages.successfully_updated") }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to user_path(current_user), notice: t("activerecord.models.post") + t("messages.successfully_deleted") }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.includes(:images, :user).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :title, :location, :date, :model, :chassis_number, :registration_number, :features, :situation)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= form_for(@post, multipart: true) do |f|
  - if @post.errors.any?
    #error_explanation
      %h2
        = pluralize(@post.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - @post.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    = f.text_field :title, class: "form-control"
  .field
    = f.label :location
    .form-group
      .input-group
        .input-group-addon 沖縄県
        = f.text_field :location, class: "form-control"
  .form-inline
    .form-group
      .field
        = f.label :date
        = f.date_select :date, {}, class: "form-control"
  .field
    = f.label :model
    = f.text_field :model, class: "form-control"
  .field
    = f.label :chassis_number
    = f.text_field :chassis_number, class: "form-control"
  .field
    = f.label :registration_number
    = f.text_field :registration_number, class: "form-control"
  .field
    = f.label :features
    = f.text_field :features, class: "form-control"
  .field
    = f.label :situation
    = f.text_field :situation, class: "form-control"
  %div
    = f.label :images
    %br
      = f.file_field :images, type: :file, multiple: true
      %span.small ＊ 画像は３点まで選択できます。Ctrlキーを押しながら画像を選択して下さい。
  .actions
    = f.submit class: "btn btn-default"
    = link_to t("links.back"), posts_path, class: "btn btn-default"

app/views/posts/edit.html.haml
.narrow
  %table.table.table-striped.table-bordered
    %tr
      %td.post-title= @post.title
    %tr
      %td
        %ul
          %li
            - if @post.images
              - @post.images.each do |image|
                = link_to image_tag(image.url(:thumb)), image.url(:medium), "data-lightbox" => image.url(:medium)
          %li= "#{t('activerecord.attributes.post.location')}: #{@post.location}"
          %li= "#{t('activerecord.attributes.post.date')}: #{@post.date.strftime('%Y/%m/%d')}"
          %li= "#{t('activerecord.attributes.post.model')}: #{@post.model}"
          %li= "#{t('activerecord.attributes.post.chassis_number')}: #{@post.chassis_number}"
          %li= "#{t('activerecord.attributes.post.registration_number')}: #{@post.registration_number}"
          %li= "#{t('activerecord.attributes.post.features')}: #{@post.features}"
          %li= "#{t('activerecord.attributes.post.situation')}: #{@post.situation}"
        .right
          .user-info
            - if user_signed_in? && @post.user == current_user
              = link_to t("links.found"), @post, :method => :delete, :data => { :confirm => t("messages.found")}, :class => "btn btn-success"
            - else
              = link_to t("activerecord.models.reply"), "#{new_reply_path}/#{@post.id}", class: "btn btn-info"

            - if @post.user && @post.user.image
              = link_to image_tag(@post.user.image.url(:thumb), height:60), @post.user.image.url(:medium), "data-lightbox" => @post.user.image.url(:medium)
            = @post.user.name
            %span.small= @post.created_at.strftime("%Y/%m/%d %H:%M")

  = link_to t("links.back"), @post, class: "btn btn-default", data: {no_turbolink: true}

app/views/posts/index.html.haml
.narrow
  .container
    .row
      .col-md-12
        .center
          %h1 沖縄のバイク盗難情報の総合掲示板「ヌスルー情報局」
      .col-md-4
        .title.strong 盗難情報が<br>検索できます
        .clear
        .subtitle ※例 車体番号、<br>ナンバープレート、<br>車種、盗難場所など
        .clear
          .form-inline
            .form-group
              = form_for Post.new, method: :get do
                = text_field_tag :keyword, params[:keyword], class: "form-control input-lg"
                = submit_tag t("links.search"), class: "btn btn-default"

        .title 配布用チラシ<br>はこちら
        .clear
        .subtitle
          ヌスルー情報局のチラシを<br>ダウンロードし印刷して<br>周囲のひとに呼びかけましょう！
        .image
          = link_to image_tag("/nusuru_s.jpg", alt: "ヌスルー情報局配布用チラシ"), "/nusuru.jpg", "data-lightbox" => "/nusuru.jpg"
          .download
            = link_to "ダウンロードはこちら", "/contents/downloadpdf/download"

      .col-md-8
        .right
          %p= link_to t("links.post.new"), new_post_path, class: "btn btn-default btn-lg"

        .float-right{data:{no_turbolink: true}}= paginate @posts
        .clear.ad-top
        %table.table.table-striped.table-bordered
          - @posts.each do |post|
            %tr
              %td.post-title
                %h2= link_to post.title, post, data: {no_turbolink: true}
            %tr
              %td
                %ul
                  %li
                    - if post.images
                      - post.images.each do |image|
                        = link_to image_tag(image.url(:thumb)), image.url(:medium), "data-lightbox" => image.url(:medium)
                  %li= "#{t('activerecord.attributes.post.location')}: #{post.location}"
                  %li= "#{t('activerecord.attributes.post.date')}: #{post.date.strftime('%Y/%m/%d')}"
                  %li= "#{t('activerecord.attributes.post.model')}: #{post.model}"
                  %li= "#{t('activerecord.attributes.post.chassis_number')}: #{post.chassis_number}"
                  %li= "#{t('activerecord.attributes.post.registration_number')}: #{post.registration_number}"
                  %li= "#{t('activerecord.attributes.post.features')}: #{post.features}"
                  %li= "#{t('activerecord.attributes.post.situation')}: #{post.situation}"
                .right
                  .user-info
                    - if user_signed_in? && post.user == current_user
                      = link_to t("links.found"), post, :method => :delete, :data => { :confirm => t("messages.found")}, :class => "btn btn-success"
                    - else
                      = link_to t("activerecord.models.reply"), "#{new_reply_path}/#{post.id}", class: "btn btn-info", data: {no_turbolink: true}
                    - if post.user && post.user.image
                      = link_to image_tag(post.user.image.url(:thumb), height:60), post.user.image.url(:medium), "data-lightbox" => post.user.image.url(:medium)
                    = post.user.name
                    %span.small= post.created_at.strftime("%Y/%m/%d %H:%M")
        .float-right{data:{no_turbolink: true}}= paginate @posts
        .clear
        - if @posts.size >= 3
          .right
            %p= link_to t("links.new") + t("activerecord.models.post"), new_post_path, class: "btn btn-default btn-lg"

app/views/posts/new.html.haml
.center
  %h2
    = t "links.new"
    = t "activerecord.models.post"
.narrow
  = render 'form'

app/views/posts/show.html.haml
.narrow
  %table.table.table-striped.table-bordered
    %tr
      %td.post-title
        %h1= @post.title
    %tr
      %td
        %ul
          %li
            - if @post.images
              - @post.images.each do |image|
                = link_to image_tag(image.url(:thumb)), image.url(:medium), "data-lightbox" => image.url(:medium)
          %li
            %strong= "#{t('activerecord.attributes.post.location')}: #{@post.location}"
          %li= "#{t('activerecord.attributes.post.date')}: #{@post.date.strftime('%Y/%m/%d')}"
          %li
            %strong= "#{t('activerecord.attributes.post.model')}: #{@post.model}"
          %li= "#{t('activerecord.attributes.post.chassis_number')}: #{@post.chassis_number}"
          %li= "#{t('activerecord.attributes.post.registration_number')}: #{@post.registration_number}"
          %li= "#{t('activerecord.attributes.post.features')}: #{@post.features}"
          %li= "#{t('activerecord.attributes.post.situation')}: #{@post.situation}"
        .right
          .user-info
            - if user_signed_in? && @post.user == current_user
              = link_to t("links.found"), @post, :method => :delete, :data => { :confirm => t("messages.found")}, :class => "btn btn-success"
            - else
              = link_to t("activerecord.models.reply"), "#{new_reply_path}/#{@post.id}", class: "btn btn-info"

            - if @post.user && @post.user.image
              = link_to image_tag(@post.user.image.url(:thumb), alt: @post.user.name, height:60), @post.user.image.url(:medium), "data-lightbox" => @post.user.image.url(:medium)
            = @post.user.name
            %span.small= @post.created_at.strftime("%Y/%m/%d %H:%M")

  = link_to t("links.back"), :back, class: "btn btn-default", data: {no_turbolink: true}